CREATE TABLE PESSOA_TF (
	codigo BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
	sexo VARCHAR(10) NOT NULL,
	email VARCHAR(100) NOT NULL,
	telefone VARCHAR(30) NOT NULL,
	cep VARCHAR(10) NOT NULL,
	logradouro VARCHAR(100) NOT NULL,
	cidade VARCHAR(80) NOT NULL,
	estado VARCHAR(50) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE PACIENTE_TF (
	codigo BIGINT NOT NULL,
	peso FLOAT NOT NULL,
	altura FLOAT NOT NULL,
	tiposanguineo VARCHAR(4) NOT NULL,
    
	CONSTRAINT FK_PAC_PESSOA FOREIGN KEY (codigo) 
    REFERENCES PESSOA_TF (codigo)
    ON UPDATE NO ACTION ON DELETE NO ACTION
) ENGINE=InnoDB;

CREATE TABLE FUNCIONARIO_TF (
	codigo BIGINT NOT NULL,
	dataContrato DATE NOT NULL,
	salario FLOAT NOT NULL,
	senhaHash VARCHAR(300) NOT NULL,

	CONSTRAINT FK_FUNC_PESSOA FOREIGN KEY (codigo) 
    REFERENCES PESSOA_TF (codigo)
    ON UPDATE NO ACTION ON DELETE NO ACTION
) ENGINE=InnoDB;

CREATE TABLE MEDICO_TF (
	codigo BIGINT NOT NULL,
	especialidade VARCHAR(100) NOT NULL,
	crm VARCHAR(50) NOT NULL,

	CONSTRAINT FK_MED_FUNC FOREIGN KEY (codigo) 
    REFERENCES FUNCIONARIO_TF (codigo) 
    ON UPDATE NO ACTION ON DELETE NO ACTION
) ENGINE=InnoDB;

CREATE TABLE ENDERECO_TF (
	cep VARCHAR(10) PRIMARY KEY NOT NULL,
	logradouro VARCHAR(100) NOT NULL,
	cidade VARCHAR(80) NOT NULL,
	estado VARCHAR(50) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE AGENDA_TF (
	codigo BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	dataAgenda VARCHAR(10) NOT NULL,
	horario VARCHAR(5) NOT NULL,
	nome VARCHAR(100) NOT NULL,
	sexo VARCHAR(2) NOT NULL,
	email VARCHAR(100) NOT NULL,
	codigoMedico BIGINT NOT NULL,

	CONSTRAINT FK_AG_MEDICO FOREIGN KEY (codigoMedico) 
    REFERENCES MEDICO_TF (codigo)
    ON UPDATE NO ACTION ON DELETE NO ACTION
) ENGINE=InnoDB;

INSERT INTO `ENDERECO_TF` (`cep`, `logradouro`, `cidade`, `estado`) VALUES
('14010-080', 'Rua Álvares Cabral', 'Ribeirão Preto', 'São Paulo'),
('38400-100', 'Av João Naves', 'Uberlândia', 'Minas Gerais'),
('38400-200', 'Rua Tiradentes', 'Uberlândia', 'Minas Gerais');